# Generated by Django 5.1.2 on 2025-12-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='skillset',
            field=models.ManyToManyField(blank=True, help_text='Навыки пользователя', to='authenticate.skillset'),
        ),
    ]
