# Generated by Django 5.1.2 on 2025-12-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_alter_customuser_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar_seed',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
